Models/ErrorViewModel.cs
namespace WebApplication1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/BiographyController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1.Controllers
{
    public class BiographyController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult ReligiousCompositions()
        {
            return View();
        }
        public IActionResult Portrait()
        {
            return View();
        }

       
        public IActionResult SelectedWorks()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
       

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Biography/Index.cshtml
<h1>Рєпін Ілля Юхимович</h1>
<div>
    <h2>1844, 5 серпня у Чугуєві на Харківщині народився знаменитий художник Рєпін Ілля Юхимович</h2>
    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Ilya_Repin_%281909%29.jpg/410px-Ilya_Repin_%281909%29.jpg"></img>
    <p>Батько художника походив із козацького роду на прізвисько Ріпа. Відслуживши 27 років, він  вийшов у відставку і одружився з Тетяною Бочаровою, теж із родини військових поселенців, 
        і зайнявся розведенням племінних коней. Родина була досить заможною. Бабуся художника тримала постоялий двір.</p>
    <p>Малювати Ілля почав ще змалку. Перші уроки малювання давав двоюрідний брат Трохим Чапигін. Пізніше хлопця віддали на навчання в корпус топографів, згодом пішов учитися іконопису в майстерню Бунакових, підробляв розписуванням храмів.</p>
    <p>У 1863 р. Рєпін вирушає підкорювати Санкт-Петербург, фарбує дахи, екіпажі, навіть відра. Паралельно вступає до малювальної школи Товариства заохочування художників, де на талановитого юнака звертає увагу художник Крамской. З другої спроби Рєпін вступає до петербурзької Академії мистецтв, яку закінчує, отримавши золоту медаль, шість років стажується в Парижі.</p>
    <p>Попри те, що Ілля Рєпін став частиною культурного світу Російської імперії, зв’язків із Україною він ніколи не поривав, лишивши на згадку цілу серію картин на українську тематику. Найвідоміша з них – «Запорожці» - написана під впливом відомого дослідника історії козацтва Дмитра Яворницького, з яким художник тісно приятелював. Його ж Рєпін і зобразив у центрі композиції в образі писаря. На отримані від картини кошти Рєпін купив собі маєток під Петербургом, де й прожив до кінця життя.</p>
    <p>Рєпін намагався підтримувати Україну не лише творчо. У 1915 р. художник  відвідав Чугуїв, маючи намір створити в рідному місті «Діловий двір» — вільні художні майстерні. Також він допомагав Спілці образотворчих мистецтв ім. В. Верещагіна в м. Миколаєві, був поважним членом Київської літературно-артистичної спілки, Київської спілки старовини й мистецтва. Його учнями були українські художники Фотій Красицький (онук Тараса Шевченка), Олександр Мурашко, Микола Пимоненко, Семен Прохоров, Ігор Грабар, Никанор Онацький, Іван Макушенко та інші.</p>
    <p>В останні дні свого життя Рєпін працював над полотнами «Зустріч гетьмана» та «Козак-бандурист із хлопчиком-джурою». У 1926 р. Рєпін задумав картину «Гопак» і до останнього мріяв про її завершення. Як згадують очевидці, навіть на порозі смерті Рєпін у забутті безперестанку водив рукою (лівою — права давно відмовила), вважаючи, що працює над своєю останньою, «красивою, веселою» картиною, про яку раніше писав у листі Яворницькому: «Навіть столітній дід навприсядки пішов. Підвипили, скачуть… Довкола веселий пейзаж: який і був…».</p>
    <p>Помер Ілля Рєпін 30 вересня 1930 р. За заповітом художника, його поховали без труни в парку його садиби «Пенати». Після розпаду Російської імперії могила художника опинилася на території Фінляндії у м.Куоккала.</p>

</div>

Views/Biography/Portrait.cshtml
<h1>Портрети роботи Рєпіна</h1>
<div class="container text-center">
    <!-- Stack the columns on mobile by making one full-width and the other half-width -->
    <div class="row">
        <div class="col-6 col-md-4">
            <figure class="figure">
                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/%D0%98%D0%BB%D1%8C%D1%8F_%D0%95._%D0%A0%D0%B5%D0%BF%D0%B8%D0%BD_-_%D0%9E%D1%82%D0%B4%D1%8B%D1%85._%D0%9F%D0%BE%D1%80%D1%82%D1%80%D0%B5%D1%82_%D0%92.%D0%90.%D0%A0%D0%B5%D0%BF%D0%B8%D0%BD%D0%B0_%281882%29.jpg/186px-%D0%98%D0%BB%D1%8C%D1%8F_%D0%95._%D0%A0%D0%B5%D0%BF%D0%B8%D0%BD_-_%D0%9E%D1%82%D0%B4%D1%8B%D1%85._%D0%9F%D0%BE%D1%80%D1%82%D1%80%D0%B5%D1%82_%D0%92.%D0%90.%D0%A0%D0%B5%D0%BF%D0%B8%D0%BD%D0%B0_%281882%29.jpg" class="figure-img img-fluid rounded" alt="...">
                <figcaption class="figure-caption text-end">«Відпочинок. Портрет В. А. Репиной, дружини художника», 1882</figcaption>
            </figure>
        </div>
        <div class="col-6 col-md-4">
            <figure class="figure">
                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Repin_bouquet.jpg/179px-Repin_bouquet.jpg" class="figure-img img-fluid rounded" alt="...">
                <figcaption class="figure-caption text-end">«Осінній букет», 1892</figcaption>
            </figure>
        </div>
        <div class="col-6 col-md-4">
            <figure class="figure">
                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/%D0%A0%D0%B5%D0%BF%D0%B8%D0%BD._%D0%A3%D0%BA%D1%80%D0%B0%D0%B8%D0%BD%D0%BA%D0%B0_%D1%83_%D0%BF%D0%BB%D0%B5%D1%82%D0%BD%D1%8F.jpg/240px-%D0%A0%D0%B5%D0%BF%D0%B8%D0%BD._%D0%A3%D0%BA%D1%80%D0%B0%D0%B8%D0%BD%D0%BA%D0%B0_%D1%83_%D0%BF%D0%BB%D0%B5%D1%82%D0%BD%D1%8F.jpg" class="figure-img img-fluid rounded" alt="...">
                <figcaption class="figure-caption text-end">«Українка біля тину», 1876</figcaption>
            </figure>
        </div>
    </div>
    <!-- Columns start at 50% wide on mobile and bump up to 33.3% wide on desktop -->
    <div class="row">
        <div class="col-6 col-md-4"><figure class="figure">
                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/%D0%97%D0%B0%D0%BF%D0%BE%D1%80%D0%BE%D0%B6%D1%81%D0%BA%D0%B8%D0%B9_%D0%BF%D0%BE%D0%BB%D0%BA%D0%BE%D0%B2%D0%BD%D0%B8%D0%BA_-_%D1%80%D0%B5%D0%BF%D0%B8%D0%BD.jpg/159px-%D0%97%D0%B0%D0%BF%D0%BE%D1%80%D0%BE%D0%B6%D1%81%D0%BA%D0%B8%D0%B9_%D0%BF%D0%BE%D0%BB%D0%BA%D0%BE%D0%B2%D0%BD%D0%B8%D0%BA_-_%D1%80%D0%B5%D0%BF%D0%B8%D0%BD.jpg" class="figure-img img-fluid rounded" alt="...">
                <figcaption class="figure-caption text-end">«Запорізький полковник», 1880</figcaption>
</figure>
</div>
        <div class="col-6 col-md-4"><figure class="figure">
                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Nikolay_II_of_Russia_by_I.Repin_%281896%2C_GIM%29.jpg/132px-Nikolay_II_of_Russia_by_I.Repin_%281896%2C_GIM%29.jpg" class="figure-img img-fluid rounded" alt="...">
                <figcaption class="figure-caption text-end">«Портрет Миколи II», 1896</figcaption>
</figure>
</div>
        <div class="col-6 col-md-4"><figure class="figure">
                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/%D0%86%D0%BB%D0%BB%D1%8F_%D0%A0%D1%94%D0%BF%D1%96%D0%BD._%D0%9F%D0%BE%D1%80%D1%82%D1%80%D0%B5%D1%82_%D0%A2%D0%B0%D1%80%D0%B0%D1%81%D0%B0_%D0%A8%D0%B5%D0%B2%D1%87%D0%B5%D0%BD%D0%BA%D0%B0.jpeg/214px-%D0%86%D0%BB%D0%BB%D1%8F_%D0%A0%D1%94%D0%BF%D1%96%D0%BD._%D0%9F%D0%BE%D1%80%D1%82%D1%80%D0%B5%D1%82_%D0%A2%D0%B0%D1%80%D0%B0%D1%81%D0%B0_%D0%A8%D0%B5%D0%B2%D1%87%D0%B5%D0%BD%D0%BA%D0%B0.jpeg" class="figure-img img-fluid rounded" alt="...">
                <figcaption class="figure-caption text-end">«Портрет Тараса Шевченка», 1888</figcaption>
</figure>
</div>
    </div>

</div>

Views/Biography/ReligiousCompositions.cshtml
<h1>Релігійні композиції</h1>
<div class="container text-center">
    <!-- Stack the columns on mobile by making one full-width and the other half-width -->
    <div class="row">
        <div class="col-6 col-md-4">
            <figure class="figure">
                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Ilja_Jefimowitsch_Repin_013.jpg/300px-Ilja_Jefimowitsch_Repin_013.jpg" class="figure-img img-fluid rounded" alt="...">
                <figcaption class="figure-caption text-end">«Христос воскрешає доньку Іаіра», 1871, Державний Російський музей, Санкт-Петербург</figcaption>
            </figure>
        </div>
        <div class="col-6 col-md-4">
            <figure class="figure">
                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Ilya_Repin_St_Nicholas_Kharkov.jpg/235px-Ilya_Repin_St_Nicholas_Kharkov.jpg" class="figure-img img-fluid rounded" alt="...">
                <figcaption class="figure-caption text-end">«Микола Мирлікійський звільняє від смертної кари трьох невинно засуджених». Варіант картини, 1890, Харківський художній музей</figcaption>
            </figure>
        </div>
        <div class="col-6 col-md-4">
            <figure class="figure">
                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/%D0%A0%D1%94%D0%BF%D1%96%D0%BD_%D0%86.%D0%AE._%D0%A5%D1%80%D0%B8%D1%81%D1%82%D0%BE%D1%81_%D1%83_%D0%93%D0%B5%D1%82%D1%81%D0%B8%D0%BC%D0%B0%D0%BD%D1%81%D1%8C%D0%BA%D0%BE%D0%BC%D1%83_%D1%81%D0%B0%D0%B4%D1%83._%D0%9A%D1%96%D0%BD%D0%B5%D1%86%D1%8C_1880-%D1%85.jpg/300px-%D0%A0%D1%94%D0%BF%D1%96%D0%BD_%D0%86.%D0%AE._%D0%A5%D1%80%D0%B8%D1%81%D1%82%D0%BE%D1%81_%D1%83_%D0%93%D0%B5%D1%82%D1%81%D0%B8%D0%BC%D0%B0%D0%BD%D1%81%D1%8C%D0%BA%D0%BE%D0%BC%D1%83_%D1%81%D0%B0%D0%B4%D1%83._%D0%9A%D1%96%D0%BD%D0%B5%D1%86%D1%8C_1880-%D1%85.jpg" class="figure-img img-fluid rounded" alt="...">
                <figcaption class="figure-caption text-end">«Христос у Гетсиманському саду». Кінець 1880-х</figcaption>
            </figure>
        </div>
    </div>
    <im
    <!-- Columns start at 50% wide on mobile and bump up to 33.3% wide on desktop -->
    <div class="row">
        <div class="col-6 col-md-4"><figure class="figure">
  <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Golgotha_by_Repin.jpg/246px-Golgotha_by_Repin.jpg" class="figure-img img-fluid rounded" alt="...">
  <figcaption class="figure-caption text-end">«Голгофа», бл. 1922, США, Принстон, Університетська галерея мистецтв</figcaption>
</figure>
</div>
        <div class="col-6 col-md-4"><figure class="figure">
  <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Job_and_his_friends.jpg/300px-Job_and_his_friends.jpg" class="figure-img img-fluid rounded" alt="...">
  <figcaption class="figure-caption text-end">«Йов Багатостраждальний та його друзі», Державний Російський музей, Санкт-Петербург</figcaption>
</figure>
</div>
        <div class="col-6 col-md-4"><figure class="figure">
  <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Ilja_Jefimowitsch_Repin_-_Saint_Nicholas_of_Myra_saves_three_innocents_from_death.jpg/286px-Ilja_Jefimowitsch_Repin_-_Saint_Nicholas_of_Myra_saves_three_innocents_from_death.jpg" class="figure-img img-fluid rounded" alt="...">
  <figcaption class="figure-caption text-end">«Микола Мирлікійський звільняє від смертної кари трьох невинно засуджених». 1888, Державний Російський музей, Санкт-Петербург</figcaption>
</figure>
</div>
    </div>

</div>

Views/Biography/SelectedWorks.cshtml
<h1>Обрані твори</h1>
<div class="container text-center">
    <!-- Stack the columns on mobile by making one full-width and the other half-width -->
    <div class="row">
        <div class="col-6 col-md-4">
            <figure class="figure">
                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Reply_of_the_Zaporozhian_Cossacks_%28sketch%2C_1893%2C_Kharkiv%29.jpg/300px-Reply_of_the_Zaporozhian_Cossacks_%28sketch%2C_1893%2C_Kharkiv%29.jpg" class="figure-img img-fluid rounded" alt="...">
                <figcaption class="figure-caption text-end">«Запорожці пишуть листа турецькому султану», 1893, Харківський художній музей</figcaption>
            </figure>
        </div>
        <div class="col-6 col-md-4">
            <figure class="figure">
                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Ilya_Repin_-_Barge_Haulers_on_the_Volga_-_Google_Art_Project.jpg/300px-Ilya_Repin_-_Barge_Haulers_on_the_Volga_-_Google_Art_Project.jpg" class="figure-img img-fluid rounded" alt="...">
                <figcaption class="figure-caption text-end">
                    Бурлаки на Волзі (картина), 1872-1873, Державний Російський музей, Петербург
                </figcaption>
            </figure>
        </div>
        <div class="col-6 col-md-4">
            <figure class="figure">
                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Ilya_Repin_-_%D0%9A%D1%80%D0%B5%D1%81%D1%82%D0%BD%D1%8B%D0%B9_%D1%85%D0%BE%D0%B4_%D0%B2_%D0%9A%D1%83%D1%80%D1%81%D0%BA%D0%BE%D0%B9_%D0%B3%D1%83%D0%B1%D0%B5%D1%80%D0%BD%D0%B8%D0%B8_-_Google_Art_Project.jpg/300px-Ilya_Repin_-_%D0%9A%D1%80%D0%B5%D1%81%D1%82%D0%BD%D1%8B%D0%B9_%D1%85%D0%BE%D0%B4_%D0%B2_%D0%9A%D1%83%D1%80%D1%81%D0%BA%D0%BE%D0%B9_%D0%B3%D1%83%D0%B1%D0%B5%D1%80%D0%BD%D0%B8%D0%B8_-_Google_Art_Project.jpg" class="figure-img img-fluid rounded" alt="...">
                <figcaption class="figure-caption text-end">«Хресна хода в Курській губернії», (1880–1883)</figcaption>
            </figure>
        </div>
    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Biography" asp-action="Index">Biography</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Biography" asp-action="ReligiousCompositions">ReligiousCompositions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Biography" asp-action="Portrait">Portrait</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Biography" asp-action="SelectedWorks">SelectedWorks</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>